import type { TextStyle } from './schema.js'

/**
 * Built-in text styles, grouped into five tone families. Each preset is
 * tuned to a research-backed pattern (see PLAN-M7 §research):
 *
 *   - news      — clean, top-anchored, high legibility on mobile.
 *   - social    — Hormozi/MrBeast Black + thick stroke + per-word pop
 *                 + one keyword accent in yellow / red / green.
 *   - cinematic — Playfair / Inter Light, large negative space, slow fade.
 *   - retro     — neon glow / arcade chrome / cyberpunk RGB-split.
 *   - playful   — Bebas / scaleIn bounce / typewriter for ngộ nghĩnh.
 *
 * `fontFamily` references one of the seven Google Fonts wired in
 * packages/remotion/src/scenes/fonts.ts — using anything outside
 * `ALLOWED_FONT_IDS` will silently fall back to the system stack at
 * render time, so user-authored styles should stick to the whitelist.
 */

/** Logical font ids the renderer guarantees to load. */
export const ALLOWED_FONT_IDS = [
  'beVietnamPro',
  'inter',
  'montserrat',
  'anton',
  'bebasNeue',
  'playfairDisplay',
  'jetBrainsMono',
  'lexend',
  'manrope',
  'oswald',
  'archivoBlack',
  'nunito',
] as const

export type AllowedFontId = (typeof ALLOWED_FONT_IDS)[number]

export const BUILT_IN_TEXT_STYLES: TextStyle[] = [
  // ── Family A — News & explainer (top-anchored, +19% engagement) ─────────
  {
    id: 'classic',
    name: 'Classic news',
    family: 'news',
    fontFamily: 'beVietnamPro',
    fontSize: 78,
    fontWeight: 700,
    letterSpacing: -0.5,
    lineHeight: 1.1,
    color: '#f4f4f6',
    background: { kind: 'none' },
    textShadow: { blur: 16, color: 'rgba(0,0,0,0.6)', offsetX: 0, offsetY: 2 },
    align: 'left',
    anchor: 'top',
    marginPct: 9,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.4,
    exitDurationSec: 0.4,
    source: 'builtin',
    scope: [],
  },
  {
    id: 'bold-news',
    name: 'Bold news',
    family: 'news',
    fontFamily: 'montserrat',
    fontSize: 92,
    fontWeight: 900,
    letterSpacing: -2,
    lineHeight: 1.0,
    color: '#ffffff',
    textStroke: { widthPx: 6, color: '#0b0b0f' },
    textShadow: { blur: 24, color: 'rgba(0,0,0,0.7)', offsetX: 0, offsetY: 4 },
    background: { kind: 'none' },
    align: 'left',
    anchor: 'top',
    marginPct: 9,
    enter: 'slideUp',
    exit: 'fade',
    enterDurationSec: 0.45,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'breaking-red',
    name: 'Breaking red',
    family: 'news',
    fontFamily: 'montserrat',
    fontSize: 84,
    fontWeight: 900,
    letterSpacing: 0,
    lineHeight: 1.05,
    color: '#ffffff',
    background: { kind: 'solid', color: '#dc2626', paddingPct: 3, radiusPx: 6, opacity: 0.95 },
    align: 'center',
    anchor: 'top',
    marginPct: 9,
    enter: 'slideDown',
    exit: 'fade',
    enterDurationSec: 0.35,
    exitDurationSec: 0.35,
    sfx: { enterSoundId: 'ding', enterVolume: 0.6, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'news-ticker',
    name: 'News ticker',
    family: 'news',
    fontFamily: 'inter',
    fontSize: 64,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: 1.2,
    color: '#ffffff',
    background: { kind: 'solid', color: '#0b0b0f', paddingPct: 2.5, radiusPx: 8, opacity: 0.92 },
    align: 'left',
    anchor: 'bottom',
    marginPct: 7,
    enter: 'slideUp',
    exit: 'fade',
    enterDurationSec: 0.35,
    exitDurationSec: 0.35,
    source: 'builtin',
    scope: ['keypoint'],
  },

  // ── Family B — TikTok / social (Hormozi-style) ──────────────────────────
  {
    id: 'tiktok-caption',
    name: 'TikTok caption',
    family: 'social',
    fontFamily: 'montserrat',
    fontSize: 84,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.0,
    color: '#ffffff',
    textStroke: { widthPx: 8, color: '#000000' },
    textShadow: { blur: 0, color: 'rgba(0,0,0,1)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: 'pop',
      enterVolume: 0.5,
      perWordSoundId: 'pop',
      perWordVolume: 0.35,
    },
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'hormozi-yellow',
    name: 'Hormozi yellow',
    family: 'social',
    fontFamily: 'montserrat',
    fontSize: 88,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.0,
    color: '#fde047', // accent yellow per research (#f7c204 family)
    textStroke: { widthPx: 8, color: '#000000' },
    textShadow: { blur: 0, color: 'rgba(0,0,0,1)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: 'pop',
      enterVolume: 0.55,
      perWordSoundId: 'pop',
      perWordVolume: 0.35,
    },
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'hormozi-green',
    name: 'Hormozi green',
    family: 'social',
    fontFamily: 'montserrat',
    fontSize: 84,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.0,
    color: '#22ff67', // saturated green per research
    textStroke: { widthPx: 8, color: '#000000' },
    textShadow: { blur: 0, color: 'rgba(0,0,0,1)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: 'pop',
      enterVolume: 0.55,
      perWordSoundId: 'pop',
      perWordVolume: 0.35,
    },
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'wordhighlight-mint',
    name: 'Word highlight (mint)',
    family: 'social',
    fontFamily: 'montserrat',
    fontSize: 74,
    fontWeight: 800,
    letterSpacing: -0.5,
    lineHeight: 1.1,
    color: '#ffffff',
    textStroke: { widthPx: 4, color: '#000000' },
    background: { kind: 'none' },
    gradientFill: { from: '#34d399', to: '#34d399', angleDeg: 0 },
    align: 'center',
    anchor: 'middle',
    marginPct: 9,
    enter: 'wordHighlight',
    exit: 'fade',
    enterDurationSec: 0.2,
    exitDurationSec: 0.35,
    sfx: { enterVolume: 0.6, perWordSoundId: 'click', perWordVolume: 0.35 },
    source: 'builtin',
    scope: ['keypoint'],
  },

  // ── Family C — Cinematic / elegant ──────────────────────────────────────
  {
    id: 'cinematic',
    name: 'Cinematic',
    family: 'cinematic',
    fontFamily: 'inter',
    fontSize: 60,
    fontWeight: 400,
    letterSpacing: 6,
    lineHeight: 1.3,
    color: '#f4f4f6',
    background: {
      kind: 'gradient',
      from: 'rgba(11,11,15,0)',
      to: 'rgba(11,11,15,0.85)',
      angleDeg: 180,
      paddingPct: 6,
      radiusPx: 0,
    },
    align: 'center',
    anchor: 'bottom',
    marginPct: 12,
    enter: 'blurReveal',
    exit: 'fade',
    enterDurationSec: 0.9,
    exitDurationSec: 0.9,
    source: 'builtin',
    scope: ['outro', 'title'],
  },
  {
    id: 'editorial-serif',
    name: 'Editorial serif',
    family: 'cinematic',
    fontFamily: 'playfairDisplay',
    fontSize: 84,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.1,
    color: '#f4f4f6',
    textShadow: { blur: 18, color: 'rgba(0,0,0,0.6)', offsetX: 0, offsetY: 4 },
    background: { kind: 'none' },
    align: 'left',
    anchor: 'middle',
    marginPct: 10,
    enter: 'maskWipe',
    exit: 'fade',
    enterDurationSec: 0.7,
    exitDurationSec: 0.6,
    source: 'builtin',
    scope: ['title', 'quote'],
  },
  {
    id: 'quote-soft',
    name: 'Quote soft',
    family: 'cinematic',
    fontFamily: 'playfairDisplay',
    fontSize: 64,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: 1.3,
    color: '#e5e5e5',
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 12,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.6,
    exitDurationSec: 0.6,
    source: 'builtin',
    scope: ['quote'],
  },
  {
    id: 'outro-glow',
    name: 'Outro glow',
    family: 'cinematic',
    fontFamily: 'inter',
    fontSize: 70,
    fontWeight: 700,
    letterSpacing: -0.5,
    lineHeight: 1.15,
    color: '#a5b4fc',
    textShadow: {
      blur: 32,
      color: 'rgba(165,180,252,0.7)',
      offsetX: 0,
      offsetY: 0,
      secondary: { blur: 60, color: 'rgba(165,180,252,0.4)', offsetX: 0, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 10,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.7,
    exitDurationSec: 0.6,
    sfx: { enterSoundId: 'sparkle', enterVolume: 0.45, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['outro'],
  },

  // ── Family D — Retro / arcade / cyberpunk ───────────────────────────────
  {
    id: 'neon-pink',
    name: 'Neon pink',
    family: 'retro',
    fontFamily: 'anton',
    fontSize: 110,
    fontWeight: 400,
    letterSpacing: 4,
    lineHeight: 0.95,
    color: '#f472b6',
    textShadow: {
      blur: 16,
      color: 'rgba(244,114,182,1)',
      offsetX: 0,
      offsetY: 0,
      secondary: { blur: 48, color: 'rgba(244,114,182,0.6)', offsetX: 0, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'scaleIn',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'neon-cyan',
    name: 'Neon cyan',
    family: 'retro',
    fontFamily: 'jetBrainsMono',
    fontSize: 76,
    fontWeight: 700,
    letterSpacing: 4,
    lineHeight: 1.05,
    color: '#67e8f9',
    textShadow: {
      blur: 16,
      color: 'rgba(103,232,249,1)',
      offsetX: 0,
      offsetY: 0,
      secondary: { blur: 48, color: 'rgba(103,232,249,0.6)', offsetX: 0, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'scaleIn',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'arcade-chrome',
    name: 'Arcade chrome',
    family: 'retro',
    fontFamily: 'anton',
    fontSize: 120,
    fontWeight: 400,
    letterSpacing: 2,
    lineHeight: 0.95,
    color: '#ffffff',
    gradientFill: { from: '#f3f4f6', to: '#94a3b8', angleDeg: 180 },
    textStroke: { widthPx: 6, color: '#1e293b' },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'slotMachine',
    exit: 'fade',
    enterDurationSec: 0.9,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'arcade-coin', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'cyberpunk-glitch',
    name: 'Cyberpunk glitch',
    family: 'retro',
    fontFamily: 'anton',
    fontSize: 104,
    fontWeight: 400,
    letterSpacing: 2,
    lineHeight: 0.95,
    color: '#ffffff',
    textShadow: {
      blur: 0,
      color: '#ff00ea',
      offsetX: -4,
      offsetY: 0,
      secondary: { blur: 0, color: '#00ffff', offsetX: 4, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'glitch',
    exit: 'fade',
    enterDurationSec: 0.4,
    exitDurationSec: 0.3,
    sfx: { enterSoundId: 'glitch', enterVolume: 0.6, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },

  // ── Family E — Playful / fun (ngộ nghĩnh) ───────────────────────────────
  {
    id: 'playful-bubble',
    name: 'Playful bubble',
    family: 'playful',
    fontFamily: 'montserrat',
    fontSize: 100,
    fontWeight: 900,
    letterSpacing: -2,
    lineHeight: 1.0,
    color: '#fef3c7',
    textStroke: { widthPx: 8, color: '#f97316' },
    textShadow: { blur: 0, color: 'rgba(249,115,22,1)', offsetX: 0, offsetY: 8 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'scaleIn',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.4,
    sfx: {
      enterSoundId: 'boing',
      enterVolume: 0.6,
      perWordSoundId: 'pop',
      perWordVolume: 0.4,
    },
    source: 'builtin',
    scope: [],
  },
  {
    id: 'bebas-impact',
    name: 'Bebas impact',
    family: 'playful',
    fontFamily: 'bebasNeue',
    fontSize: 140,
    fontWeight: 400,
    letterSpacing: 2,
    lineHeight: 0.9,
    color: '#ffffff',
    textStroke: { widthPx: 4, color: '#000000' },
    textShadow: { blur: 24, color: 'rgba(0,0,0,0.7)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'slideUp',
    exit: 'fade',
    enterDurationSec: 0.45,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'typewriter-mono',
    name: 'Typewriter',
    family: 'playful',
    fontFamily: 'jetBrainsMono',
    fontSize: 56,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: 1.3,
    color: '#ffffff',
    background: { kind: 'none' },
    align: 'left',
    anchor: 'middle',
    marginPct: 10,
    enter: 'typewriter',
    exit: 'fade',
    enterDurationSec: 1.0,
    exitDurationSec: 0.35,
    sfx: {
      enterVolume: 0.6,
      perWordSoundId: 'typewriter-key',
      perWordVolume: 0.3,
    },
    source: 'builtin',
    scope: ['quote', 'keypoint'],
  },
  {
    id: 'gradient-pop',
    name: 'Gradient pop',
    family: 'playful',
    fontFamily: 'montserrat',
    fontSize: 100,
    fontWeight: 900,
    letterSpacing: -2,
    lineHeight: 1.0,
    color: '#ffffff',
    gradientFill: { from: '#a5b4fc', to: '#f472b6', angleDeg: 135 },
    textStroke: { widthPx: 4, color: '#0b0b0f' },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.55,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.35 },
    source: 'builtin',
    scope: ['title'],
  },

  // ── Family F — Content-tone presets ────────────────────────────────────
  // Eight color-coded looks the orchestrator should reach for when an
  // article's topic is unmistakable. Each preset pairs a topic-appropriate
  // font with WCAG-safe high-contrast color + halo so the text stays
  // legible across varied background photography.
  {
    id: 'crime-red',
    name: 'Crime red',
    family: 'social',
    fontFamily: 'oswald',
    fontSize: 92,
    fontWeight: 700,
    letterSpacing: 2,
    lineHeight: 1.05,
    color: '#fef2f2',
    textStroke: { widthPx: 6, color: '#7f1d1d' },
    textShadow: {
      blur: 0,
      color: 'rgba(127,29,29,1)',
      offsetX: 0,
      offsetY: 6,
      secondary: { blur: 32, color: 'rgba(220,38,38,0.7)', offsetX: 0, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'slideDown',
    exit: 'fade',
    enterDurationSec: 0.35,
    exitDurationSec: 0.35,
    sfx: { enterSoundId: 'ding', enterVolume: 0.7, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'tech-cyan',
    name: 'Tech cyan',
    family: 'retro',
    fontFamily: 'jetBrainsMono',
    fontSize: 72,
    fontWeight: 700,
    letterSpacing: 1,
    lineHeight: 1.1,
    color: '#67e8f9',
    textShadow: {
      blur: 16,
      color: 'rgba(34,211,238,0.9)',
      offsetX: 0,
      offsetY: 0,
      secondary: { blur: 40, color: 'rgba(6,182,212,0.5)', offsetX: 0, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.4,
    exitDurationSec: 0.35,
    sfx: { enterSoundId: 'glitch', enterVolume: 0.55, perWordVolume: 0.35 },
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'finance-gold',
    name: 'Finance gold',
    family: 'social',
    fontFamily: 'archivoBlack',
    fontSize: 92,
    fontWeight: 400,
    letterSpacing: -1,
    lineHeight: 1.05,
    color: '#fde047',
    textStroke: { widthPx: 6, color: '#1c1917' },
    textShadow: { blur: 0, color: 'rgba(28,25,23,1)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: 'arcade-coin',
      enterVolume: 0.55,
      perWordSoundId: 'pop',
      perWordVolume: 0.35,
    },
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'wellness-mint',
    name: 'Wellness mint',
    family: 'news',
    fontFamily: 'manrope',
    fontSize: 76,
    fontWeight: 800,
    letterSpacing: -0.5,
    lineHeight: 1.15,
    color: '#ffffff',
    textShadow: { blur: 20, color: 'rgba(6,78,59,0.65)', offsetX: 0, offsetY: 4 },
    background: { kind: 'solid', color: '#0f766e', paddingPct: 2.8, radiusPx: 10, opacity: 0.9 },
    align: 'center',
    anchor: 'top',
    marginPct: 10,
    enter: 'slideDown',
    exit: 'fade',
    enterDurationSec: 0.45,
    exitDurationSec: 0.4,
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'entertainment-pink',
    name: 'Entertainment pink',
    family: 'playful',
    fontFamily: 'nunito',
    fontSize: 92,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.05,
    color: '#fce7f3',
    textStroke: { widthPx: 6, color: '#9d174d' },
    textShadow: { blur: 0, color: 'rgba(157,23,77,1)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'scaleIn',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'sparkle', enterVolume: 0.6, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'sports-yellow',
    name: 'Sports yellow',
    family: 'social',
    fontFamily: 'archivoBlack',
    fontSize: 100,
    fontWeight: 400,
    letterSpacing: -1,
    lineHeight: 1.0,
    color: '#fde047',
    textStroke: { widthPx: 8, color: '#0b0b0f' },
    textShadow: { blur: 0, color: 'rgba(0,0,0,1)', offsetX: 0, offsetY: 8 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.45,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: 'whoosh-short',
      enterVolume: 0.6,
      perWordSoundId: 'pop',
      perWordVolume: 0.4,
    },
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'lifestyle-orange',
    name: 'Lifestyle orange',
    family: 'playful',
    fontFamily: 'lexend',
    fontSize: 76,
    fontWeight: 800,
    letterSpacing: -0.5,
    lineHeight: 1.15,
    color: '#fff7ed',
    textShadow: { blur: 20, color: 'rgba(124,45,18,0.7)', offsetX: 0, offsetY: 4 },
    background: { kind: 'solid', color: '#ea580c', paddingPct: 2.8, radiusPx: 12, opacity: 0.92 },
    align: 'left',
    anchor: 'bottom',
    marginPct: 8,
    enter: 'slideUp',
    exit: 'fade',
    enterDurationSec: 0.4,
    exitDurationSec: 0.4,
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'nature-green',
    name: 'Nature green',
    family: 'cinematic',
    fontFamily: 'lexend',
    fontSize: 72,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: 1.2,
    color: '#ecfdf5',
    textShadow: { blur: 24, color: 'rgba(6,78,59,0.75)', offsetX: 0, offsetY: 4 },
    background: {
      kind: 'gradient',
      from: 'rgba(6,78,59,0)',
      to: 'rgba(6,78,59,0.88)',
      angleDeg: 180,
      paddingPct: 6,
      radiusPx: 0,
    },
    align: 'center',
    anchor: 'bottom',
    marginPct: 11,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.8,
    exitDurationSec: 0.8,
    source: 'builtin',
    scope: ['title', 'outro'],
  },

  // ── Family G — Sprint-1 motion-driven (karaoke + letter-stagger) ───────
  // These rely on `wordBoundaries` (Edge TTS) or a per-character cascade.
  // The motion drives the full segment, not just a 0.4s intro, so the
  // text stays alive throughout the read.
  {
    id: 'karaoke-bold',
    name: 'Karaoke bold',
    family: 'social',
    fontFamily: 'montserrat',
    fontSize: 88,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.0,
    color: '#ffffff',
    textStroke: { widthPx: 8, color: '#000000' },
    textShadow: { blur: 0, color: 'rgba(0,0,0,1)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'karaoke',
    exit: 'fade',
    enterDurationSec: 0.2,
    exitDurationSec: 0.35,
    karaokeMode: 'pop',
    karaokeAccentColor: '#fde047',
    karaokeIdleColor: 'rgba(255,255,255,0.28)',
    sfx: { enterSoundId: 'pop', enterVolume: 0.5, perWordVolume: 0 },
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'karaoke-news',
    name: 'Karaoke news',
    family: 'news',
    fontFamily: 'inter',
    fontSize: 72,
    fontWeight: 800,
    letterSpacing: -0.5,
    lineHeight: 1.15,
    color: '#f4f4f6',
    textShadow: { blur: 16, color: 'rgba(0,0,0,0.7)', offsetX: 0, offsetY: 2 },
    background: { kind: 'none' },
    align: 'left',
    anchor: 'bottom',
    marginPct: 9,
    enter: 'karaoke',
    exit: 'fade',
    enterDurationSec: 0.2,
    exitDurationSec: 0.35,
    karaokeMode: 'fill',
    karaokeAccentColor: '#67e8f9',
    karaokeIdleColor: 'rgba(244,244,246,0.32)',
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'karaoke-underline',
    name: 'Karaoke underline',
    family: 'social',
    fontFamily: 'manrope',
    fontSize: 76,
    fontWeight: 800,
    letterSpacing: 0,
    lineHeight: 1.15,
    color: '#ffffff',
    textShadow: { blur: 12, color: 'rgba(0,0,0,0.6)', offsetX: 0, offsetY: 2 },
    background: { kind: 'none' },
    align: 'left',
    anchor: 'bottom',
    marginPct: 9,
    enter: 'karaoke',
    exit: 'fade',
    enterDurationSec: 0.2,
    exitDurationSec: 0.35,
    karaokeMode: 'underline',
    karaokeAccentColor: '#fbbf24',
    karaokeIdleColor: 'rgba(255,255,255,0.55)',
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'stagger-cinematic',
    name: 'Stagger cinematic',
    family: 'cinematic',
    fontFamily: 'playfairDisplay',
    fontSize: 84,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.1,
    color: '#fafafa',
    textShadow: { blur: 28, color: 'rgba(0,0,0,0.7)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 9,
    enter: 'letterStagger',
    exit: 'fade',
    enterDurationSec: 1.6,
    exitDurationSec: 0.5,
    staggerStep: 0.045,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.4, perWordVolume: 0 },
    source: 'builtin',
    scope: ['title', 'outro'],
  },
  {
    id: 'stagger-impact',
    name: 'Stagger impact',
    family: 'news',
    fontFamily: 'bebasNeue',
    fontSize: 132,
    fontWeight: 400,
    letterSpacing: 4,
    lineHeight: 0.95,
    color: '#fafafa',
    textStroke: { widthPx: 4, color: '#0b0b0f' },
    textShadow: { blur: 20, color: 'rgba(0,0,0,0.8)', offsetX: 0, offsetY: 6 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'top',
    marginPct: 12,
    enter: 'letterStagger',
    exit: 'fade',
    enterDurationSec: 1.2,
    exitDurationSec: 0.4,
    staggerStep: 0.03,
    sfx: { enterSoundId: 'ding', enterVolume: 0.6, perWordVolume: 0 },
    source: 'builtin',
    scope: ['title'],
  },
]

const BUILT_IN_BY_ID: Record<string, TextStyle> = Object.fromEntries(
  BUILT_IN_TEXT_STYLES.map((s) => [s.id, s])
)

/**
 * Resolve a text style id against built-ins + the project's userTextStyles
 * (added via `data/user-styles/*.json` or saved from Studio). User styles
 * win on id collisions so users can override built-ins by reusing the id.
 */
export function findTextStyle(
  id: string | undefined,
  userStyles: TextStyle[] = []
): TextStyle | null {
  if (!id) return null
  const user = userStyles.find((s) => s.id === id)
  if (user) return user
  return BUILT_IN_BY_ID[id] ?? null
}

/** Default style used when nothing else resolves. */
export const DEFAULT_TEXT_STYLE_ID = 'classic'

/**
 * Default render variants. The orchestrator overrides these by tone, but
 * the baseline trio aims for maximum visual contrast so the user can pick
 * an obvious favourite:
 *
 *   A — Classic news        clean, top-anchored, low-effort default.
 *   B — Hormozi social      caps + thick stroke + yellow accent + word pop.
 *   C — Cinematic editorial Playfair + slow fade + outro glow.
 */
export const DEFAULT_VARIANTS: ReadonlyArray<{
  id: string
  label: string
  textStyleBySceneKind: Record<string, string>
}> = [
  {
    id: 'A',
    label: 'Classic',
    textStyleBySceneKind: {
      title: 'classic',
      keypoint: 'news-ticker',
      quote: 'quote-soft',
      outro: 'cinematic',
    },
  },
  {
    id: 'B',
    label: 'Hormozi social',
    textStyleBySceneKind: {
      title: 'bold-news',
      keypoint: 'hormozi-yellow',
      quote: 'typewriter-mono',
      outro: 'outro-glow',
    },
  },
  {
    id: 'C',
    label: 'Cinematic',
    textStyleBySceneKind: {
      title: 'editorial-serif',
      keypoint: 'wordhighlight-mint',
      quote: 'quote-soft',
      outro: 'cinematic',
    },
  },
]
