import type { TextStyle } from './schema.js'

/**
 * Built-in text styles, grouped into five tone families:
 *
 *   - news      — clean, legible, default-safe
 *   - social    — TikTok-ish, per-word punchy
 *   - cinematic — slow, premium, large negative space
 *   - retro     — neon / arcade / cyberpunk
 *   - playful   — bouncy / oversized / ngộ nghĩnh
 *
 * Each entry is plain data so the render bundle, the Studio picker, and
 * the MCP orchestrator all share the same source of truth.
 *
 * Conventions:
 *   - `fontSize` is the logical px at 1080-wide canvas. `useResponsive` in
 *     the Remotion scenes scales it for 16:9 / 1:1.
 *   - `marginPct` is a percentage of the shorter canvas edge.
 *   - `sfx.enterSoundId` and `sfx.perWordSoundId` reference ids from
 *     `packages/shared/src/sfx.ts`.
 */
export const BUILT_IN_TEXT_STYLES: TextStyle[] = [
  // ── Family A — News & explainer ────────────────────────────────────────
  {
    id: 'classic',
    name: 'Classic news',
    family: 'news',
    fontFamily: 'Be Vietnam Pro, Inter, sans-serif',
    fontSize: 84,
    fontWeight: 700,
    letterSpacing: -1,
    lineHeight: 1.05,
    color: '#f4f4f6',
    background: { kind: 'none' },
    align: 'left',
    anchor: 'bottom',
    marginPct: 8,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.4,
    exitDurationSec: 0.4,
    source: 'builtin',
    scope: [],
  },
  {
    id: 'bold-news',
    name: 'Bold news',
    family: 'news',
    fontFamily: 'Inter, sans-serif',
    fontSize: 92,
    fontWeight: 900,
    letterSpacing: -1.5,
    lineHeight: 1.05,
    color: '#ffffff',
    textStroke: { widthPx: 4, color: '#000000' },
    background: { kind: 'none' },
    align: 'left',
    anchor: 'bottom',
    marginPct: 8,
    enter: 'slideUp',
    exit: 'fade',
    enterDurationSec: 0.45,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'breaking-red',
    name: 'Breaking red',
    family: 'news',
    fontFamily: 'Inter, sans-serif',
    fontSize: 80,
    fontWeight: 900,
    letterSpacing: 0,
    lineHeight: 1.1,
    color: '#ffffff',
    background: { kind: 'solid', color: '#dc2626', paddingPct: 3, radiusPx: 4, opacity: 0.95 },
    align: 'center',
    anchor: 'top',
    marginPct: 10,
    enter: 'slideDown',
    exit: 'fade',
    enterDurationSec: 0.35,
    exitDurationSec: 0.35,
    sfx: { enterSoundId: 'ding', enterVolume: 0.6, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'news-ticker',
    name: 'News ticker',
    family: 'news',
    fontFamily: 'Inter, sans-serif',
    fontSize: 60,
    fontWeight: 700,
    letterSpacing: 0,
    lineHeight: 1.2,
    color: '#ffffff',
    background: { kind: 'solid', color: '#0b0b0f', paddingPct: 2.5, radiusPx: 6, opacity: 0.92 },
    align: 'left',
    anchor: 'bottom',
    marginPct: 6,
    enter: 'slideUp',
    exit: 'fade',
    enterDurationSec: 0.35,
    exitDurationSec: 0.35,
    source: 'builtin',
    scope: ['keypoint'],
  },

  // ── Family B — TikTok / social ─────────────────────────────────────────
  {
    id: 'tiktok-caption',
    name: 'TikTok caption',
    family: 'social',
    fontFamily: 'Inter, sans-serif',
    fontSize: 72,
    fontWeight: 900,
    letterSpacing: -0.5,
    lineHeight: 1.1,
    color: '#ffffff',
    textStroke: { widthPx: 6, color: '#000000' },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: 'pop',
      enterVolume: 0.5,
      perWordSoundId: 'pop',
      perWordVolume: 0.35,
    },
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'bold-yellow',
    name: 'Bold yellow',
    family: 'social',
    fontFamily: 'Inter, sans-serif',
    fontSize: 80,
    fontWeight: 900,
    letterSpacing: -0.5,
    lineHeight: 1.05,
    color: '#fde047',
    textStroke: { widthPx: 6, color: '#000000' },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: 'pop',
      enterVolume: 0.55,
      perWordSoundId: 'pop',
      perWordVolume: 0.35,
    },
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'wordhighlight-mint',
    name: 'Word highlight (mint)',
    family: 'social',
    fontFamily: 'Inter, sans-serif',
    fontSize: 70,
    fontWeight: 700,
    letterSpacing: -0.5,
    lineHeight: 1.15,
    color: '#ffffff',
    background: { kind: 'none' },
    // The active-word chip color is read by WordHighlight via gradientFill.from.
    gradientFill: { from: '#34d399', to: '#34d399', angleDeg: 0 },
    align: 'center',
    anchor: 'bottom',
    marginPct: 10,
    enter: 'wordHighlight',
    exit: 'fade',
    enterDurationSec: 0.2,
    exitDurationSec: 0.35,
    sfx: { enterSoundId: undefined, enterVolume: 0.6, perWordSoundId: 'click', perWordVolume: 0.35 },
    source: 'builtin',
    scope: ['keypoint'],
  },
  {
    id: 'gradient-pop',
    name: 'Gradient pop',
    family: 'social',
    fontFamily: 'Inter, sans-serif',
    fontSize: 96,
    fontWeight: 900,
    letterSpacing: -2,
    lineHeight: 1.0,
    color: '#ffffff',
    gradientFill: { from: '#a5b4fc', to: '#f472b6', angleDeg: 135 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.55,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.35 },
    source: 'builtin',
    scope: ['title'],
  },

  // ── Family C — Cinematic / elegant ─────────────────────────────────────
  {
    id: 'cinematic',
    name: 'Cinematic',
    family: 'cinematic',
    fontFamily: 'Inter, sans-serif',
    fontSize: 64,
    fontWeight: 300,
    letterSpacing: 4,
    lineHeight: 1.25,
    color: '#ffffff',
    background: {
      kind: 'gradient',
      from: 'rgba(11,11,15,0)',
      to: 'rgba(11,11,15,0.85)',
      angleDeg: 180,
      paddingPct: 6,
      radiusPx: 0,
    },
    align: 'center',
    anchor: 'bottom',
    marginPct: 10,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.8,
    exitDurationSec: 0.8,
    source: 'builtin',
    scope: ['outro', 'title'],
  },
  {
    id: 'quote-soft',
    name: 'Quote soft',
    family: 'cinematic',
    fontFamily: 'Playfair Display, Georgia, serif',
    fontSize: 60,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: 1.3,
    color: '#e5e5e5',
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 12,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.6,
    exitDurationSec: 0.6,
    source: 'builtin',
    scope: ['quote'],
  },
  {
    id: 'outro-glow',
    name: 'Outro glow',
    family: 'cinematic',
    fontFamily: 'Inter, sans-serif',
    fontSize: 72,
    fontWeight: 700,
    letterSpacing: -0.5,
    lineHeight: 1.15,
    color: '#a5b4fc',
    textShadow: { blur: 24, color: 'rgba(165,180,252,0.6)', offsetX: 0, offsetY: 0 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 10,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.6,
    exitDurationSec: 0.6,
    sfx: { enterSoundId: 'sparkle', enterVolume: 0.45, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['outro'],
  },
  {
    id: 'gradient-wipe',
    name: 'Gradient wipe',
    family: 'cinematic',
    fontFamily: 'Inter, sans-serif',
    fontSize: 88,
    fontWeight: 900,
    letterSpacing: -1.5,
    lineHeight: 1.0,
    color: '#ffffff',
    gradientFill: { from: '#fef3c7', to: '#a5b4fc', angleDeg: 90 },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'gradientWipe',
    exit: 'fade',
    enterDurationSec: 0.9,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-long', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title', 'outro'],
  },

  // ── Family D — Retro / arcade / cyberpunk ──────────────────────────────
  {
    id: 'neon-pink',
    name: 'Neon pink',
    family: 'retro',
    fontFamily: 'Inter, sans-serif',
    fontSize: 88,
    fontWeight: 900,
    letterSpacing: 0,
    lineHeight: 1.0,
    color: '#f472b6',
    textShadow: {
      blur: 12,
      color: 'rgba(244,114,182,0.9)',
      offsetX: 0,
      offsetY: 0,
      secondary: { blur: 32, color: 'rgba(244,114,182,0.5)', offsetX: 0, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'scaleIn',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'neon-cyan',
    name: 'Neon cyan',
    family: 'retro',
    fontFamily: 'JetBrains Mono, monospace',
    fontSize: 80,
    fontWeight: 800,
    letterSpacing: 2,
    lineHeight: 1.05,
    color: '#67e8f9',
    textShadow: {
      blur: 12,
      color: 'rgba(103,232,249,0.9)',
      offsetX: 0,
      offsetY: 0,
      secondary: { blur: 32, color: 'rgba(103,232,249,0.5)', offsetX: 0, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'scaleIn',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'whoosh-short', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'arcade-chrome',
    name: 'Arcade chrome',
    family: 'retro',
    fontFamily: 'Inter, sans-serif',
    fontSize: 96,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.0,
    color: '#ffffff',
    gradientFill: { from: '#f3f4f6', to: '#94a3b8', angleDeg: 180 },
    textStroke: { widthPx: 5, color: '#1e293b' },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'slotMachine',
    exit: 'fade',
    enterDurationSec: 0.9,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'arcade-coin', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },
  {
    id: 'cyberpunk-glitch',
    name: 'Cyberpunk glitch',
    family: 'retro',
    fontFamily: 'Inter, sans-serif',
    fontSize: 86,
    fontWeight: 900,
    letterSpacing: 0,
    lineHeight: 1.0,
    color: '#ffffff',
    // RGB-split via two-layer shadow (magenta on -, cyan on +).
    textShadow: {
      blur: 0,
      color: '#ff00ff',
      offsetX: -3,
      offsetY: 0,
      secondary: { blur: 0, color: '#00ffff', offsetX: 3, offsetY: 0 },
    },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'wordPop',
    exit: 'fade',
    enterDurationSec: 0.4,
    exitDurationSec: 0.3,
    sfx: { enterSoundId: 'glitch', enterVolume: 0.6, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title'],
  },

  // ── Family E — Playful / fun ───────────────────────────────────────────
  {
    id: 'playful-bubble',
    name: 'Playful bubble',
    family: 'playful',
    fontFamily: 'Inter, sans-serif',
    fontSize: 88,
    fontWeight: 900,
    letterSpacing: -1,
    lineHeight: 1.05,
    color: '#fef3c7',
    textStroke: { widthPx: 6, color: '#f97316' },
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'scaleIn',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.4,
    sfx: {
      enterSoundId: 'boing',
      enterVolume: 0.6,
      perWordSoundId: 'pop',
      perWordVolume: 0.4,
    },
    source: 'builtin',
    scope: [],
  },
  {
    id: 'slot-reveal',
    name: 'Slot reveal',
    family: 'playful',
    fontFamily: 'Inter, sans-serif',
    fontSize: 80,
    fontWeight: 900,
    letterSpacing: -0.5,
    lineHeight: 1.05,
    color: '#ffffff',
    background: {
      kind: 'gradient',
      from: '#f472b6',
      to: '#fde047',
      angleDeg: 135,
      paddingPct: 3,
      radiusPx: 12,
    },
    align: 'center',
    anchor: 'middle',
    marginPct: 8,
    enter: 'slotMachine',
    exit: 'fade',
    enterDurationSec: 0.8,
    exitDurationSec: 0.4,
    sfx: { enterSoundId: 'arcade-coin', enterVolume: 0.55, perWordVolume: 0.4 },
    source: 'builtin',
    scope: ['title', 'keypoint'],
  },
  {
    id: 'typewriter-mono',
    name: 'Typewriter',
    family: 'playful',
    fontFamily: 'JetBrains Mono, monospace',
    fontSize: 56,
    fontWeight: 600,
    letterSpacing: 0,
    lineHeight: 1.3,
    color: '#ffffff',
    background: { kind: 'none' },
    align: 'left',
    anchor: 'middle',
    marginPct: 10,
    enter: 'typewriter',
    exit: 'fade',
    enterDurationSec: 1.0,
    exitDurationSec: 0.35,
    sfx: {
      enterSoundId: undefined,
      enterVolume: 0.6,
      perWordSoundId: 'typewriter-key',
      perWordVolume: 0.3,
    },
    source: 'builtin',
    scope: ['quote', 'keypoint'],
  },
  {
    id: 'minimal-mono',
    name: 'Minimal mono',
    family: 'playful',
    fontFamily: 'JetBrains Mono, monospace',
    fontSize: 56,
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: 1.3,
    color: '#cfd6df',
    background: { kind: 'none' },
    align: 'center',
    anchor: 'middle',
    marginPct: 12,
    enter: 'fade',
    exit: 'fade',
    enterDurationSec: 0.5,
    exitDurationSec: 0.5,
    source: 'builtin',
    scope: [],
  },
]

const BUILT_IN_BY_ID: Record<string, TextStyle> = Object.fromEntries(
  BUILT_IN_TEXT_STYLES.map((s) => [s.id, s])
)

/**
 * Resolve a text style id against built-ins + the project's userTextStyles
 * (added via `data/user-styles/*.json` or saved from Studio). User styles
 * win on id collisions so users can override built-ins by reusing the id.
 */
export function findTextStyle(
  id: string | undefined,
  userStyles: TextStyle[] = []
): TextStyle | null {
  if (!id) return null
  const user = userStyles.find((s) => s.id === id)
  if (user) return user
  return BUILT_IN_BY_ID[id] ?? null
}

/** Default style used when nothing else resolves. */
export const DEFAULT_TEXT_STYLE_ID = 'classic'

/**
 * Default render variants matched to article tone. The orchestrator may
 * rewrite these per project, e.g. swap C with a Family-D set for a tech
 * piece, or with Family-E for a playful topic.
 */
export const DEFAULT_VARIANTS: ReadonlyArray<{
  id: string
  label: string
  textStyleBySceneKind: Record<string, string>
}> = [
  {
    id: 'A',
    label: 'Classic',
    textStyleBySceneKind: {
      title: 'classic',
      keypoint: 'classic',
      quote: 'quote-soft',
      outro: 'cinematic',
    },
  },
  {
    id: 'B',
    label: 'Bold news',
    textStyleBySceneKind: {
      title: 'bold-news',
      keypoint: 'bold-yellow',
      quote: 'typewriter-mono',
      outro: 'outro-glow',
    },
  },
  {
    id: 'C',
    label: 'Cinematic',
    textStyleBySceneKind: {
      title: 'gradient-pop',
      keypoint: 'tiktok-caption',
      quote: 'quote-soft',
      outro: 'cinematic',
    },
  },
]
